import type {
  StudentUser,
  TeacherUser,
  PersonalUser,
  Problem,
  Battle,
  Classroom,
  LeaderboardEntry,
  ActivityEvent,
} from '../types';

export const mockStudent: StudentUser = {
  id: 'student-1',
  name: 'Alex Johnson',
  email: 'alex@student.devclash.demo',
  role: 'student',
  avatar: undefined,
  createdAt: '2024-01-15T10:00:00Z',
  duelRating: {
    rating: 1642,
    level: 17,
    xp: 28900,
    xpToNextLevel: 3100,
    weeklyXpGain: 42,
    trend: 'up',
    rank: 'Gold II',
    percentile: 78,
  },
  practiceRating: {
    rating: 1287,
    level: 12,
    xp: 14400,
    xpToNextLevel: 2100,
    weeklyXpGain: 85,
    trend: 'up',
    rank: 'Silver III',
    percentile: 62,
  },
  adaptiveRating: {
    rating: 1519,
    level: 15,
    xp: 22500,
    xpToNextLevel: 1900,
    weeklyXpGain: 67,
    trend: 'stable',
    rank: 'Gold III',
    percentile: 71,
  },
  statistics: {
    totalBattles: 84,
    battlesWon: 52,
    battlesLost: 32,
    winRate: 62,
    problemsSolved: 156,
    problemsAttempted: 203,
    adaptiveSessions: 28,
    totalXp: 65800,
    currentStreak: 7,
    maxStreak: 14,
    averageRating: 1483,
  },
};

export const mockTeacher: TeacherUser = {
  id: 'teacher-1',
  name: 'Dr. Sarah Williams',
  email: 'sarah@devclash.demo',
  role: 'teacher',
  avatar: undefined,
  createdAt: '2023-09-01T08:00:00Z',
  classrooms: [
    {
      id: 'class-1',
      name: 'CS 101 - Data Structures',
      code: 'CS101-F24',
      studentCount: 34,
      createdAt: '2024-01-10T09:00:00Z',
      isActive: true,
    },
    {
      id: 'class-2',
      name: 'CS 201 - Algorithms',
      code: 'CS201-F24',
      studentCount: 28,
      createdAt: '2024-01-12T14:00:00Z',
      isActive: true,
    },
    {
      id: 'class-3',
      name: 'Advanced Competitive Programming',
      code: 'ACP-F24',
      studentCount: 12,
      createdAt: '2024-02-01T10:00:00Z',
      isActive: false,
    },
  ],
  totalStudents: 74,
  analytics: {
    totalClassrooms: 3,
    totalStudents: 74,
    activeStudents: 58,
    averageDuelRating: 1423,
    averagePracticeRating: 1187,
    averageAdaptiveRating: 1356,
    topStudents: [
      { rank: 1, userId: 's-1', name: 'Emma Chen', avatar: undefined, rating: 1892, level: 22, xp: 45200, winRate: 78, problemsSolved: 234 },
      { rank: 2, userId: 's-2', name: 'Marcus Johnson', avatar: undefined, rating: 1756, level: 19, xp: 38900, winRate: 71, problemsSolved: 198 },
      { rank: 3, userId: 's-3', name: 'Sofia Rodriguez', avatar: undefined, rating: 1689, level: 18, xp: 34200, winRate: 69, problemsSolved: 176 },
      { rank: 4, userId: 's-4', name: 'David Kim', avatar: undefined, rating: 1634, level: 17, xp: 31100, winRate: 65, problemsSolved: 154 },
      { rank: 5, userId: 's-5', name: 'Priya Patel', avatar: undefined, rating: 1598, level: 16, xp: 28900, winRate: 63, problemsSolved: 142 },
    ],
    recentActivity: [
      { id: 'act-1', type: 'battle', userId: 's-1', userName: 'Emma Chen', description: 'won a Duel against Marcus Johnson', metadata: { ratingChange: +24 }, timestamp: '2024-03-15T14:32:00Z' },
      { id: 'act-2', type: 'problem', userId: 's-3', userName: 'Sofia Rodriguez', description: 'solved "Two Sum" (Easy)', metadata: { xpGain: 50 }, timestamp: '2024-03-15T13:45:00Z' },
      { id: 'act-3', type: 'adaptive', userId: 's-2', userName: 'Marcus Johnson', description: 'completed Adaptive Session (+45 XP)', metadata: { ratingChange: +12 }, timestamp: '2024-03-15T12:20:00Z' },
      { id: 'act-4', type: 'classroom', userId: 'teacher-1', userName: 'Dr. Sarah Williams', description: 'created classroom "CS 301 - Advanced Topics"', metadata: {}, timestamp: '2024-03-15T10:00:00Z' },
      { id: 'act-5', type: 'achievement', userId: 's-5', userName: 'Priya Patel', description: 'earned "Streak Master" badge', metadata: { streak: 14 }, timestamp: '2024-03-14T18:30:00Z' },
    ],
  },
};

export const mockPersonal: PersonalUser = {
  id: 'personal-1',
  name: 'Jordan Lee',
  email: 'jordan@devclash.demo',
  role: 'personal',
  avatar: undefined,
  createdAt: '2024-02-20T16:00:00Z',
  duelRating: {
    rating: 1823,
    level: 20,
    xp: 39800,
    xpToNextLevel: 1200,
    weeklyXpGain: 124,
    trend: 'up',
    rank: 'Platinum I',
    percentile: 89,
  },
  practiceRating: {
    rating: 1654,
    level: 17,
    xp: 30200,
    xpToNextLevel: 2800,
    weeklyXpGain: 98,
    trend: 'up',
    rank: 'Gold I',
    percentile: 81,
  },
  adaptiveRating: {
    rating: 1789,
    level: 19,
    xp: 36700,
    xpToNextLevel: 1500,
    weeklyXpGain: 112,
    trend: 'up',
    rank: 'Platinum III',
    percentile: 86,
  },
  statistics: {
    totalBattles: 142,
    battlesWon: 98,
    battlesLost: 44,
    winRate: 69,
    problemsSolved: 287,
    problemsAttempted: 342,
    adaptiveSessions: 56,
    totalXp: 106700,
    currentStreak: 12,
    maxStreak: 23,
    averageRating: 1755,
  },
};

export const mockProblems: Problem[] = [
  {
    id: 'prob-1',
    title: 'Two Sum',
    description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    difficulty: 'easy',
    tags: ['Arrays', 'Hash Maps'],
    constraints: '2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9\nOnly one valid answer exists.',
    examples: [
      { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 9, we return [0, 1].' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]', explanation: 'Because nums[1] + nums[2] == 6, we return [1, 2].' },
      { input: 'nums = [3,3], target = 6', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 6, we return [0, 1].' },
    ],
    hints: [
      'A brute force approach checks all pairs in O(n^2) time. Can we do better using extra memory?',
      'Consider using a hash map to store the numbers you have seen so far and their indices.',
      'For each element x, check if (target - x) exists in the hash map.'
    ],
    testCases: [
      { id: 'tc-1', input: '[2, 7, 11, 15], 9', expectedOutput: '[0, 1]', isPublic: true },
      { id: 'tc-2', input: '[3, 2, 4], 6', expectedOutput: '[1, 2]', isPublic: true },
      { id: 'tc-3', input: '[3, 3], 6', expectedOutput: '[0, 1]', isPublic: true },
      { id: 'tc-4', input: '[1, 5, 8, 3], 9', expectedOutput: '[1, 2]', isPublic: false },
      { id: 'tc-5', input: '[-1, -2, -3, -4, -5], -8', expectedOutput: '[2, 4]', isPublic: false },
    ],
    starterCode: {
      javascript: 'function twoSum(nums, target) {\n  // Map value -> index\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement), i];\n    }\n    map.set(nums[i], i);\n  }\n  return [];\n}',
      python: 'def twoSum(nums: list[int], target: int) -> list[int]:\n    seen = {}\n    for i, num in enumerate(nums):\n        comp = target - num\n        if comp in seen:\n            return [seen[comp], i]\n        seen[num] = i\n    return []',
      java: 'class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) return new int[]{map.get(comp), i};\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}',
      cpp: 'class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        unordered_map<int, int> seen;\n        for (int i = 0; i < nums.size(); ++i) {\n            int comp = target - nums[i];\n            if (seen.count(comp)) return {seen[comp], i};\n            seen[nums[i]] = i;\n        }\n        return {};\n    }\n};',
    },
    solved: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    statistics: {
      totalSubmissions: 12453,
      acceptedSubmissions: 8934,
      acceptanceRate: 71.7,
      averageTime: 42,
      averageMemory: 38.5,
    },
  },
  {
    id: 'prob-2',
    title: 'Valid Parentheses',
    description: 'Given a string s containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
    difficulty: 'easy',
    tags: ['Strings', 'Stack'],
    constraints: '1 <= s.length <= 10^4\ns consists of parentheses only \'()[]{}\'.',
    examples: [
      { input: 's = "()"', output: 'true' },
      { input: 's = "()[]{}"', output: 'true' },
      { input: 's = "(]"', output: 'false' },
    ],
    hints: [
      'Think about using a Stack LIFO data structure.',
      'Push open brackets onto the stack. When encounter a closing bracket, verify the top matches.',
      'Check if stack is completely empty at the end.'
    ],
    testCases: [
      { id: 'tc-1', input: '"()"', expectedOutput: 'true', isPublic: true },
      { id: 'tc-2', input: '"()[]{}"', expectedOutput: 'true', isPublic: true },
      { id: 'tc-3', input: '"(]"', expectedOutput: 'false', isPublic: true },
      { id: 'tc-4', input: '"([)]"', expectedOutput: 'false', isPublic: false },
      { id: 'tc-5', input: '"{[]}"', expectedOutput: 'true', isPublic: false },
    ],
    starterCode: {
      javascript: 'function isValid(s) {\n  const stack = [];\n  const map = { ")": "(", "}": "{", "]": "[" };\n  for (const char of s) {\n    if (char in map) {\n      if (stack.pop() !== map[char]) return false;\n    } else {\n      stack.push(char);\n    }\n  }\n  return stack.length === 0;\n}',
      python: 'def isValid(s: str) -> bool:\n    stack = []\n    pairs = {")": "(", "}": "{", "]": "["}\n    for char in s:\n        if char in pairs:\n            if not stack or stack.pop() != pairs[char]:\n                return False\n        else:\n            stack.append(char)\n    return len(stack) == 0',
      java: 'class Solution {\n    public boolean isValid(String s) {\n        // Your code here\n        return true;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    bool isValid(string s) {\n        // Your code here\n        return true;\n    }\n};',
    },
    solved: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
    statistics: {
      totalSubmissions: 9812,
      acceptedSubmissions: 6734,
      acceptanceRate: 68.6,
      averageTime: 36,
      averageMemory: 35.1,
    },
  },
  {
    id: 'prob-3',
    title: 'Longest Substring Without Repeating Characters',
    description: 'Given a string s, find the length of the longest substring without repeating characters.',
    difficulty: 'medium',
    tags: ['Strings', 'Hash Maps'],
    constraints: '0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.',
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: 'The answer is "abc", with the length of 3.' },
      { input: 's = "bbbbb"', output: '1', explanation: 'The answer is "b", with the length of 1.' },
      { input: 's = "pwwkew"', output: '3', explanation: 'The answer is "wke", with the length of 3.' },
    ],
    hints: [
      'Use a sliding window defined by two pointers [left, right].',
      'Store the last seen index of each character in a map or array to slide left pointer forward.'
    ],
    testCases: [
      { id: 'tc-1', input: '"abcabcbb"', expectedOutput: '3', isPublic: true },
      { id: 'tc-2', input: '"bbbbb"', expectedOutput: '1', isPublic: true },
      { id: 'tc-3', input: '"pwwkew"', expectedOutput: '3', isPublic: true },
      { id: 'tc-4', input: '""', expectedOutput: '0', isPublic: false },
      { id: 'tc-5', input: '"dvdf"', expectedOutput: '3', isPublic: false },
    ],
    starterCode: {
      javascript: 'function lengthOfLongestSubstring(s) {\n  let maxLen = 0;\n  let left = 0;\n  const seen = new Map();\n  for (let right = 0; right < s.length; right++) {\n    if (seen.has(s[right])) {\n      left = Math.max(left, seen.get(s[right]) + 1);\n    }\n    seen.set(s[right], right);\n    maxLen = Math.max(maxLen, right - left + 1);\n  }\n  return maxLen;\n}',
      python: 'def lengthOfLongestSubstring(s: str) -> int:\n    seen = {}\n    max_len = left = 0\n    for right, char in enumerate(s):\n        if char in seen:\n            left = max(left, seen[char] + 1)\n        seen[char] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len',
      java: 'class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        // Your code here\n        return 0;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        // Your code here\n        return 0;\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
    statistics: {
      totalSubmissions: 8932,
      acceptedSubmissions: 4123,
      acceptanceRate: 46.2,
      averageTime: 78,
      averageMemory: 41.2,
    },
  },
  {
    id: 'prob-4',
    title: 'Merge Intervals',
    description: 'Given an array of intervals where intervals[i] = [start_i, end_i], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.',
    difficulty: 'medium',
    tags: ['Arrays', 'Sorting'],
    constraints: '1 <= intervals.length <= 10^4\nintervals[i].length == 2\n0 <= start_i <= end_i <= 10^4',
    examples: [
      { input: 'intervals = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]', explanation: 'Since intervals [1,3] and [2,6] overlap, merge them into [1,6].' },
      { input: 'intervals = [[1,4],[4,5]]', output: '[[1,5]]', explanation: 'Intervals [1,4] and [4,5] are considered overlapping.' },
    ],
    hints: [
      'Sort the intervals by their start times first.',
      'Iterate through the sorted intervals. If the current interval overlaps with the previous merged interval, merge them by updating end time.'
    ],
    testCases: [
      { id: 'tc-1', input: '[[1,3],[2,6],[8,10],[15,18]]', expectedOutput: '[[1,6],[8,10],[15,18]]', isPublic: true },
      { id: 'tc-2', input: '[[1,4],[4,5]]', expectedOutput: '[[1,5]]', isPublic: true },
      { id: 'tc-3', input: '[[1,4],[0,4]]', expectedOutput: '[[0,4]]', isPublic: false },
      { id: 'tc-4', input: '[[1,4],[2,3]]', expectedOutput: '[[1,4]]', isPublic: false },
      { id: 'tc-5', input: '[[6,8]]', expectedOutput: '[[6,8]]', isPublic: false },
    ],
    starterCode: {
      javascript: 'function merge(intervals) {\n  if (!intervals.length) return [];\n  intervals.sort((a, b) => a[0] - b[0]);\n  const merged = [intervals[0]];\n  for (let i = 1; i < intervals.length; i++) {\n    const last = merged[merged.length - 1];\n    if (intervals[i][0] <= last[1]) {\n      last[1] = Math.max(last[1], intervals[i][1]);\n    } else {\n      merged.push(intervals[i]);\n    }\n  }\n  return merged;\n}',
      python: 'def merge(intervals: list[list[int]]) -> list[list[int]]:\n    intervals.sort(key=lambda x: x[0])\n    merged = []\n    for interval in intervals:\n        if not merged or merged[-1][1] < interval[0]:\n            merged.append(interval)\n        else:\n            merged[-1][1] = max(merged[-1][1], interval[1])\n    return merged',
      java: 'class Solution {\n    public int[][] merge(int[][] intervals) {\n        // Your code here\n        return intervals;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    vector<vector<int>> merge(vector<vector<int>>& intervals) {\n        // Your code here\n        return intervals;\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-04T00:00:00Z',
    statistics: {
      totalSubmissions: 6720,
      acceptedSubmissions: 3420,
      acceptanceRate: 50.8,
      averageTime: 85,
      averageMemory: 44.1,
    },
  },
  {
    id: 'prob-5',
    title: 'Coin Change',
    description: 'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\n\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.\n\nYou may assume that you have an infinite number of each kind of coin.',
    difficulty: 'medium',
    tags: ['Dynamic Programming', 'Recursion'],
    constraints: '1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4',
    examples: [
      { input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '11 = 5 + 5 + 1' },
      { input: 'coins = [2], amount = 3', output: '-1' },
      { input: 'coins = [1], amount = 0', output: '0' },
    ],
    hints: [
      'Define dp[i] as the minimum coins needed for amount i.',
      'dp[i] = min(dp[i - c] + 1) for all c in coins where i >= c.'
    ],
    testCases: [
      { id: 'tc-1', input: '[1,2,5], 11', expectedOutput: '3', isPublic: true },
      { id: 'tc-2', input: '[2], 3', expectedOutput: '-1', isPublic: true },
      { id: 'tc-3', input: '[1], 0', expectedOutput: '0', isPublic: true },
      { id: 'tc-4', input: '[1,3,4,5], 7', expectedOutput: '2', isPublic: false },
      { id: 'tc-5', input: '[186,419,83,408], 6249', expectedOutput: '20', isPublic: false },
    ],
    starterCode: {
      javascript: 'function coinChange(coins, amount) {\n  const dp = new Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (let i = 1; i <= amount; i++) {\n    for (const c of coins) {\n      if (i >= c) dp[i] = Math.min(dp[i], dp[i - c] + 1);\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}',
      python: 'def coinChange(coins: list[int], amount: int) -> int:\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for c in coins:\n            if i >= c:\n                dp[i] = min(dp[i], dp[i - c] + 1)\n    return dp[amount] if dp[amount] != float("inf") else -1',
      java: 'class Solution {\n    public int coinChange(int[] coins, int amount) {\n        // Your code here\n        return -1;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int coinChange(vector<int>& coins, int amount) {\n        // Your code here\n        return -1;\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
    statistics: {
      totalSubmissions: 5410,
      acceptedSubmissions: 2240,
      acceptanceRate: 41.4,
      averageTime: 110,
      averageMemory: 46.8,
    },
  },
  {
    id: 'prob-6',
    title: 'Course Schedule',
    description: 'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [a_i, b_i] indicates that you must take course b_i first if you want to take course a_i.\n\nReturn true if you can finish all courses. Otherwise, return false.',
    difficulty: 'medium',
    tags: ['Graphs', 'Recursion'],
    constraints: '1 <= numCourses <= 2000\n0 <= prerequisites.length <= 5000\nprerequisites[i].length == 2\n0 <= a_i, b_i < numCourses',
    examples: [
      { input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true', explanation: 'There are a total of 2 courses to take. To take course 1 you should have finished course 0. So it is possible.' },
      { input: 'numCourses = 2, prerequisites = [[1,0],[0,1]]', output: 'false', explanation: 'Course 1 requires 0, and course 0 requires 1. A cycle exists, so impossible.' },
    ],
    hints: [
      'This is equivalent to detecting whether a cycle exists in a directed graph.',
      'Use Kahn\'s algorithm (topological sort with in-degrees) or DFS with visited states.'
    ],
    testCases: [
      { id: 'tc-1', input: '2, [[1,0]]', expectedOutput: 'true', isPublic: true },
      { id: 'tc-2', input: '2, [[1,0],[0,1]]', expectedOutput: 'false', isPublic: true },
      { id: 'tc-3', input: '4, [[1,0],[2,0],[3,1],[3,2]]', expectedOutput: 'true', isPublic: false },
      { id: 'tc-4', input: '3, [[0,1],[1,2],[2,0]]', expectedOutput: 'false', isPublic: false },
      { id: 'tc-5', input: '1, []', expectedOutput: 'true', isPublic: false },
    ],
    starterCode: {
      javascript: 'function canFinish(numCourses, prerequisites) {\n  const inDegree = new Array(numCourses).fill(0);\n  const adj = Array.from({ length: numCourses }, () => []);\n  for (const [course, pre] of prerequisites) {\n    adj[pre].push(course);\n    inDegree[course]++;\n  }\n  const queue = [];\n  for (let i = 0; i < numCourses; i++) {\n    if (inDegree[i] === 0) queue.push(i);\n  }\n  let count = 0;\n  while (queue.length) {\n    const node = queue.shift();\n    count++;\n    for (const next of adj[node]) {\n      inDegree[next]--;\n      if (inDegree[next] === 0) queue.push(next);\n    }\n  }\n  return count === numCourses;\n}',
      python: 'def canFinish(numCourses: int, prerequisites: list[list[int]]) -> bool:\n    from collections import deque, defaultdict\n    in_degree = [0] * numCourses\n    adj = defaultdict(list)\n    for course, pre in prerequisites:\n        adj[pre].append(course)\n        in_degree[course] += 1\n    queue = deque([i for i in range(numCourses) if in_degree[i] == 0])\n    visited = 0\n    while queue:\n        node = queue.popleft()\n        visited += 1\n        for nxt in adj[node]:\n            in_degree[nxt] -= 1\n            if in_degree[nxt] == 0:\n                queue.append(nxt)\n    return visited == numCourses',
      java: 'class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        // Your code here\n        return true;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {\n        // Your code here\n        return true;\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
    statistics: {
      totalSubmissions: 4890,
      acceptedSubmissions: 2210,
      acceptanceRate: 45.2,
      averageTime: 125,
      averageMemory: 52.3,
    },
  },
  {
    id: 'prob-7',
    title: 'Median of Two Sorted Arrays',
    description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays in O(log (m+n)) runtime.',
    difficulty: 'hard',
    tags: ['Arrays', 'Binary Search'],
    constraints: 'nums1.length == m\nnums2.length == n\n0 <= m <= 1000\n0 <= n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6',
    examples: [
      { input: 'nums1 = [1,3], nums2 = [2]', output: '2.00000', explanation: 'merged array = [1,2,3] and median is 2.' },
      { input: 'nums1 = [1,2], nums2 = [3,4]', output: '2.50000', explanation: 'merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.' },
    ],
    hints: [
      'To achieve O(log(m+n)), binary search across the smaller array.',
      'Partition both arrays such that left halves contain (m + n + 1) / 2 elements and maxLeft <= minRight.'
    ],
    testCases: [
      { id: 'tc-1', input: '[1, 3], [2]', expectedOutput: '2.00000', isPublic: true },
      { id: 'tc-2', input: '[1, 2], [3, 4]', expectedOutput: '2.50000', isPublic: true },
      { id: 'tc-3', input: '[0, 0], [0, 0]', expectedOutput: '0.00000', isPublic: false },
      { id: 'tc-4', input: '[], [1]', expectedOutput: '1.00000', isPublic: false },
      { id: 'tc-5', input: '[2], []', expectedOutput: '2.00000', isPublic: false },
    ],
    starterCode: {
      javascript: 'function findMedianSortedArrays(nums1, nums2) {\n  // Your code here\n}',
      python: 'def findMedianSortedArrays(nums1, nums2):\n    # Your code here',
      java: 'class Solution {\n    public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        // Your code here\n    }\n}',
      cpp: 'class Solution {\npublic:\n    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n        // Your code here\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-07T00:00:00Z',
    statistics: {
      totalSubmissions: 5678,
      acceptedSubmissions: 1892,
      acceptanceRate: 33.3,
      averageTime: 156,
      averageMemory: 45.8,
    },
  },
  {
    id: 'prob-8',
    title: 'Validate Binary Search Tree',
    description: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST).\n\nA valid BST is defined as follows:\n- The left subtree of a node contains only nodes with keys strictly less than the node\'s key.\n- The right subtree of a node contains only nodes with keys strictly greater than the node\'s key.\n- Both the left and right subtrees must also be binary search trees.',
    difficulty: 'medium',
    tags: ['Trees', 'Recursion'],
    constraints: 'The number of nodes in the tree is in the range [1, 10^4].\n-2^31 <= Node.val <= 2^31 - 1',
    examples: [
      { input: 'root = [2,1,3]', output: 'true' },
      { input: 'root = [5,1,4,null,null,3,6]', output: 'false', explanation: 'The root node\'s value is 5 but its right child\'s value is 4.' },
    ],
    hints: [
      'Can you pass a valid range [min, max] down through recursive calls?',
      'Alternatively, perform an in-order traversal; the values should strictly increase.'
    ],
    testCases: [
      { id: 'tc-1', input: '[2,1,3]', expectedOutput: 'true', isPublic: true },
      { id: 'tc-2', input: '[5,1,4,null,null,3,6]', expectedOutput: 'false', isPublic: true },
      { id: 'tc-3', input: '[1,1]', expectedOutput: 'false', isPublic: false },
      { id: 'tc-4', input: '[10,5,15,null,null,6,20]', expectedOutput: 'false', isPublic: false },
      { id: 'tc-5', input: '[2147483647]', expectedOutput: 'true', isPublic: false },
    ],
    starterCode: {
      javascript: 'function isValidBST(root) {\n  function validate(node, min, max) {\n    if (!node) return true;\n    if (node.val <= min || node.val >= max) return false;\n    return validate(node.left, min, node.val) && validate(node.right, node.val, max);\n  }\n  return validate(root, -Infinity, Infinity);\n}',
      python: 'def isValidBST(root) -> bool:\n    def validate(node, low=-float("inf"), high=float("inf")):\n        if not node:\n            return True\n        if not (low < node.val < high):\n            return False\n        return validate(node.left, low, node.val) and validate(node.right, node.val, high)\n    return validate(root)',
      java: 'class Solution {\n    public boolean isValidBST(TreeNode root) {\n        // Your code here\n        return true;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    bool isValidBST(TreeNode* root) {\n        // Your code here\n        return true;\n    }\n};',
    },
    solved: false,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
    statistics: {
      totalSubmissions: 7120,
      acceptedSubmissions: 3690,
      acceptanceRate: 51.8,
      averageTime: 62,
      averageMemory: 43.4,
    },
  },
];

export const mockBattles: Battle[] = [
  {
    id: 'battle-1',
    battleCode: 'DC-7F29K',
    isRanked: true,
    status: 'completed',
    mode: 'duel',
    participants: [
      { userId: 'student-1', name: 'Alex Johnson', rating: 1642, status: 'passed', score: 92, testCasesPassed: 5, totalTestCases: 5 },
      { userId: 'opp-1', name: 'Ryan Chen', avatar: undefined, rating: 1587, status: 'passed', score: 78, testCasesPassed: 4, totalTestCases: 5 },
    ],
    problem: mockProblems[0],
    startedAt: '2024-03-14T18:00:00Z',
    endedAt: '2024-03-14T18:25:00Z',
    timeLimit: 30,
    language: 'javascript',
    result: {
      winnerId: 'student-1',
      isVictory: true,
      scores: { 'student-1': 92, 'opp-1': 78 },
      duration: 540,
      ratingChange: 38,
      xpGained: 120,
      newRating: 1680,
      streak: 6,
      submissions: [
        { userId: 'student-1', code: '// solution', language: 'javascript', status: 'accepted', score: 92, submittedAt: '2024-03-14T18:22:00Z' },
        { userId: 'opp-1', code: '// solution', language: 'javascript', status: 'accepted', score: 78, submittedAt: '2024-03-14T18:24:00Z' },
      ],
    },
  },
  {
    id: 'battle-2',
    battleCode: 'DC-8M34L',
    isRanked: true,
    status: 'completed',
    mode: 'duel',
    participants: [
      { userId: 'student-1', name: 'Alex Johnson', rating: 1642, status: 'failed', score: 45, testCasesPassed: 2, totalTestCases: 5 },
      { userId: 'opp-2', name: 'Sarah Kim', avatar: undefined, rating: 1723, status: 'passed', score: 88, testCasesPassed: 5, totalTestCases: 5 },
    ],
    problem: mockProblems[2],
    startedAt: '2024-03-14T16:00:00Z',
    endedAt: '2024-03-14T16:18:00Z',
    timeLimit: 30,
    language: 'python',
    result: {
      winnerId: 'opp-2',
      isVictory: false,
      scores: { 'student-1': 45, 'opp-2': 88 },
      duration: 720,
      ratingChange: -18,
      xpGained: 25,
      newRating: 1624,
      streak: 0,
      submissions: [
        { userId: 'student-1', code: '// solution', language: 'python', status: 'wrong', score: 45, submittedAt: '2024-03-14T16:15:00Z' },
        { userId: 'opp-2', code: '// solution', language: 'python', status: 'accepted', score: 88, submittedAt: '2024-03-14T16:12:00Z' },
      ],
    },
  },
];

export const mockClassrooms: Classroom[] = [
  {
    id: 'class-1',
    name: 'CS 101 - Data Structures',
    code: 'CSE-A7X92',
    subject: 'Computer Science',
    section: 'Section A',
    description: 'Introduction to fundamental data structures, search algorithms, and algorithmic complexity.',
    teacherId: 'teacher-1',
    studentCount: 5,
    isActive: true,
    students: [
      { userId: 's-1', name: 'Emma Chen', email: 'emma@student.devclash.demo', joinedAt: '2024-01-15T09:00:00Z', duelRating: 1892, practiceRating: 1634, adaptiveRating: 1756, problemsSolved: 142, battles: 64, accuracy: 88, isActive: true, lastActive: '2024-03-15T14:32:00Z' },
      { userId: 's-2', name: 'Marcus Johnson', email: 'marcus@student.devclash.demo', joinedAt: '2024-01-15T09:00:00Z', duelRating: 1756, practiceRating: 1523, adaptiveRating: 1645, problemsSolved: 118, battles: 52, accuracy: 82, isActive: true, lastActive: '2024-03-15T12:20:00Z' },
      { userId: 's-3', name: 'Sofia Rodriguez', email: 'sofia@student.devclash.demo', joinedAt: '2024-01-16T09:00:00Z', duelRating: 1689, practiceRating: 1456, adaptiveRating: 1587, problemsSolved: 95, battles: 41, accuracy: 79, isActive: true, lastActive: '2024-03-15T13:45:00Z' },
      { userId: 's-4', name: 'David Kim', email: 'david@student.devclash.demo', joinedAt: '2024-01-16T09:00:00Z', duelRating: 1634, practiceRating: 1389, adaptiveRating: 1512, problemsSolved: 74, battles: 29, accuracy: 68, isActive: false, lastActive: '2024-03-08T10:00:00Z' },
      { userId: 's-5', name: 'Priya Patel', email: 'priya@student.devclash.demo', joinedAt: '2024-01-17T09:00:00Z', duelRating: 1598, practiceRating: 1345, adaptiveRating: 1478, problemsSolved: 62, battles: 25, accuracy: 71, isActive: true, lastActive: '2024-03-14T18:30:00Z' },
    ],
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    settings: {
      allowDuel: true,
      allowPractice: true,
      allowAdaptive: true,
      visibility: 'private',
    },
  },
  {
    id: 'class-2',
    name: 'CS 201 - Advanced Algorithms',
    code: 'CSE-B4K18',
    subject: 'Computer Science',
    section: 'Section B',
    description: 'Dynamic programming, graph theory, greedy strategies, and competitive problem solving.',
    teacherId: 'teacher-1',
    studentCount: 3,
    isActive: true,
    students: [
      { userId: 's-1', name: 'Emma Chen', email: 'emma@student.devclash.demo', joinedAt: '2024-01-15T09:00:00Z', duelRating: 1892, practiceRating: 1634, adaptiveRating: 1756, problemsSolved: 142, battles: 64, accuracy: 88, isActive: true, lastActive: '2024-03-15T14:32:00Z' },
      { userId: 's-2', name: 'Marcus Johnson', email: 'marcus@student.devclash.demo', joinedAt: '2024-01-15T09:00:00Z', duelRating: 1756, practiceRating: 1523, adaptiveRating: 1645, problemsSolved: 118, battles: 52, accuracy: 82, isActive: true, lastActive: '2024-03-15T12:20:00Z' },
      { userId: 's-6', name: 'Lucas Vance', email: 'lucas@student.devclash.demo', joinedAt: '2024-02-01T10:00:00Z', duelRating: 1540, practiceRating: 1290, adaptiveRating: 1420, problemsSolved: 48, battles: 18, accuracy: 64, isActive: true, lastActive: '2024-03-13T11:15:00Z' },
    ],
    createdAt: '2024-01-12T14:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    settings: {
      allowDuel: true,
      allowPractice: true,
      allowAdaptive: true,
      visibility: 'private',
    },
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: 'user-1', name: 'CyberCoder', avatar: undefined, rating: 2847, level: 35, xp: 115600, winRate: 84, problemsSolved: 412 },
  { rank: 2, userId: 'user-2', name: 'AlgoMaster', avatar: undefined, rating: 2723, level: 33, xp: 102300, winRate: 81, problemsSolved: 387 },
  { rank: 3, userId: 'user-3', name: 'CodeNinja', avatar: undefined, rating: 2654, level: 32, xp: 95600, winRate: 79, problemsSolved: 356 },
  { rank: 4, userId: 'user-4', name: 'BinaryBeast', avatar: undefined, rating: 2589, level: 31, xp: 89400, winRate: 77, problemsSolved: 334 },
  { rank: 5, userId: 'user-5', name: 'LogicLord', avatar: undefined, rating: 2534, level: 30, xp: 83200, winRate: 75, problemsSolved: 312 },
  { rank: 6, userId: 'user-6', name: 'SyntaxSamurai', avatar: undefined, rating: 2478, level: 29, xp: 77800, winRate: 73, problemsSolved: 298 },
  { rank: 7, userId: 'user-7', name: 'DebugDiva', avatar: undefined, rating: 2412, level: 28, xp: 72100, winRate: 71, problemsSolved: 276 },
  { rank: 8, userId: 'user-8', name: 'RecursiveRay', avatar: undefined, rating: 2356, level: 27, xp: 66800, winRate: 69, problemsSolved: 254 },
  { rank: 9, userId: 'user-9', name: 'HeapHero', avatar: undefined, rating: 2298, level: 26, xp: 61900, winRate: 67, problemsSolved: 238 },
  { rank: 10, userId: 'user-10', name: 'TreeTrekker', avatar: undefined, rating: 2245, level: 25, xp: 57200, winRate: 65, problemsSolved: 221 },
];

export const mockActivity: ActivityEvent[] = [
  { id: 'act-1', type: 'battle', userId: 'student-1', userName: 'Alex Johnson', description: 'won a Duel against Ryan Chen (+24 rating)', metadata: { ratingChange: 24 }, timestamp: '2024-03-15T14:32:00Z' },
  { id: 'act-2', type: 'problem', userId: 'student-1', userName: 'Alex Johnson', description: 'solved "Longest Substring" (Medium)', metadata: { xpGain: 120 }, timestamp: '2024-03-15T11:20:00Z' },
  { id: 'act-3', type: 'adaptive', userId: 'student-1', userName: 'Alex Johnson', description: 'completed Adaptive Session (+67 XP)', metadata: { ratingChange: 12 }, timestamp: '2024-03-14T19:45:00Z' },
  { id: 'act-4', type: 'battle', userId: 'student-1', userName: 'Alex Johnson', description: 'lost a Duel to Sarah Kim (-18 rating)', metadata: { ratingChange: -18 }, timestamp: '2024-03-14T16:10:00Z' },
  { id: 'act-5', type: 'achievement', userId: 'student-1', userName: 'Alex Johnson', description: 'earned "Weekly Warrior" badge', metadata: { streak: 7 }, timestamp: '2024-03-13T20:00:00Z' },
];